### PR TITLE
Update io.github.koromelodev.mindmate.yml

### PR DESCRIPTION
**Pull request by KoromeloDev**

### CODE REVIEW

**Comment by hfiguiere** [comment]
the beta branch name is reserved...

you just added the app on flathub-beta :-/

**Comment by KoromeloDev** [comment]
> the beta branch name is reserved...
> 
> you just added the app on flathub-beta :-/

And how can I fix my mistake?

**Comment by hfiguiere** [comment]
@barthalion ^^^^

**Comment by barthalion** [comment]
Just let it be; we will start removing inactive beta builds at some point.

**Pull request closed without merging**
